### PR TITLE
Introduced `get-version-status` support

### PR DESCRIPTION
**Pull request by indapublic**
Based on my [previous PR](https://github.com/piavart/rustore-client/pull/3), so should be reviewed after I assume.

https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/get-version-status

### CODE REVIEW

**Comment by piavart** [comment]
great!

**Comment by indapublic** [comment]
@piavart Thank you for so quick review. Could you release your npm package asap if possible?

**Comment by piavart** [comment]
@indapublic Yes, give me 5 minutes

**Comment by piavart** [comment]
@indapublic version 0.2.1

**Comment by indapublic** [comment]
@piavart Awesome, thank you so much.

**Pull request merged**
